version: "3.8"
services:
  backend:
    depends_on:
      - db

    env_file: ./backend/.env

    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    
    expose: 
      - "8080"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
    driver: local
